setwd("C:/Avinash/Coursera/ExploratoryDataAnalysis/Project1")
fileUrl <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(fileUrl, destfile = "exdata_data_household_power_consumption.zip")
unzip(zipfile = "exdata_data_household_power_consumption.zip", exdir = "C:/Avinash/Coursera/ExploratoryDataAnalysis/Project1" , overwrite = TRUE)
gap <- read.table("household_power_consumption.txt",header = TRUE,sep = ";",stringsAsFactors=FALSE, dec=".")
gapss <- gap[gap$Date %in% c("1/2/2007","2/2/2007"),] 
xwday <- strptime(paste(gapss$Date, gapss$Time, sep = " "), "%d/%m/%Y %H:%M:%S")
gaps <- as.numeric(gapss$Global_active_power)
grps <- as.numeric(gapss$Global_reactive_power)
vlts <- as.numeric(gapss$Voltage)
ysbm1 <- as.numeric(gapss$Sub_metering_1)
ysbm2 <- as.numeric(gapss$Sub_metering_2)
ysbm3 <- as.numeric(gapss$Sub_metering_3)

png("plot4.png", width=480, height=480)
par(mfrow = c(2,2))
plot(xwday, gaps, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(xwday , vlts , type="l", xlab="datetime", ylab="Voltage")
plot(xwday , ysbm1 , type="l", ylab="Energy Submetering", xlab="")
lines(xwday, ysbm2 , type="l", col="red")
lines(xwday, ysbm3 , type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd=2, col=c("black", "red", "blue"), bty="n")
plot(xwday, grps, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
